stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    outs:
    - data/interim
  imputation:
    cmd: python src/imputation/imputation.py
    deps:
    - data/interim/merged.csv
    - src/imputation/imputation.py
    outs:
    - data/imputed
  build_features:
    cmd: python src/features/build_features.py
    deps:
    - data/imputed/imputation.csv
    - src/features/build_features.py
    outs:
    - data/final_model
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/final_model/model_build.csv
    - src/models/train_model.py
    outs:
    - references
