stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    outs:
    - data/interim
  imputation:
    cmd: python src/imputation/imputation.py
    deps:
    - data/interim/merged.csv
    - src/imputation/imputation.py
    outs:
    - data/imputed
